name: coruja

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    depends_on:
      - ollama
      - postgres
      - tika
    restart: always

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    restart: always
  
  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    restart: always

  tika:
    build:
      context: .
      dockerfile: tika.Dockerfile
    restart: always