name: coruja

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    depends_on:
      - ollama
      - postgres
      - tika
      - valkey
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 bot.py"]
    ports:
      - 5678:5678
    restart: always

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    restart: always
  
  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always

  tika:
    build:
      context: .
      dockerfile: tika.Dockerfile
    restart: always
  
  valkey:
    image: valkey/valkey:8
    restart: always