name: coruja

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    depends_on:
      - ollama
      - tika
    restart: always

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    restart: always

  tika:
    build:
      context: .
      dockerfile: tika.Dockerfile
    restart: always